version: "3"
services:

  app_service:
    build:
      context: app_service
      dockerfile: Dockerfile
    ports:
      - "8000:50051"

  mqtt_service:
    build:
      context: mqtt
      dockerfile: Dockerfile
    ports:
      - "8001:50051"
    depends_on:
      - app_service

  influxdb_service:
    build:
      context: influxdb
      dockerfile: Dockerfile
    ports:
      - "8002:50051"
    depends_on:
      - app_service

  logic_service:
    build:
      context: logic
      dockerfile: Dockerfile
    ports:
      - "8003:50051"
    depends_on:
      - app_service
