version: "3"
services:

  database_service:
    build:
      context: database
      dockerfile: Dockerfile
    ports:
      - "8000:50051"

  influxdb_service:
    build:
      context: influxdb
      dockerfile: Dockerfile
    ports:
      - "8002:50051"

  mqtt_service:
    build:
      context: mqtt
      dockerfile: Dockerfile
    ports:
      - "8001:50051"

  user_api:
    build:
      context: user_api
      dockerfile: Dockerfile
    ports:
      - "8004:8000"