# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.protos import database_pb2 as app_dot_protos_dot_database__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DatabaseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddRoom = channel.unary_unary(
                '/database.DatabaseService/AddRoom',
                request_serializer=app_dot_protos_dot_database__pb2.AddRoomRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_database__pb2.AddRoomResponse.FromString,
                )
        self.GetRoom = channel.unary_unary(
                '/database.DatabaseService/GetRoom',
                request_serializer=app_dot_protos_dot_database__pb2.GetRoomRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_database__pb2.GetRoomResponse.FromString,
                )
        self.GetAllRooms = channel.unary_unary(
                '/database.DatabaseService/GetAllRooms',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=app_dot_protos_dot_database__pb2.GetAllRoomsResponse.FromString,
                )
        self.AddDevice = channel.unary_unary(
                '/database.DatabaseService/AddDevice',
                request_serializer=app_dot_protos_dot_database__pb2.AddDeviceRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_database__pb2.AddDeviceResponse.FromString,
                )
        self.GetDevicesInRoom = channel.unary_unary(
                '/database.DatabaseService/GetDevicesInRoom',
                request_serializer=app_dot_protos_dot_database__pb2.GetDevicesInRoomRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_database__pb2.GetDevicesInRoomResponse.FromString,
                )
        self.AddUser = channel.unary_unary(
                '/database.DatabaseService/AddUser',
                request_serializer=app_dot_protos_dot_database__pb2.AddUserRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_database__pb2.AddUserResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/database.DatabaseService/GetUser',
                request_serializer=app_dot_protos_dot_database__pb2.GetUserRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_database__pb2.GetUserResponse.FromString,
                )
        self.SetUserPreferences = channel.unary_unary(
                '/database.DatabaseService/SetUserPreferences',
                request_serializer=app_dot_protos_dot_database__pb2.SetUserPreferencesRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.AddUserToRoom = channel.unary_unary(
                '/database.DatabaseService/AddUserToRoom',
                request_serializer=app_dot_protos_dot_database__pb2.AddUserToRoomRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RemoveUserFromRoom = channel.unary_unary(
                '/database.DatabaseService/RemoveUserFromRoom',
                request_serializer=app_dot_protos_dot_database__pb2.RemoveUserFromRoomRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetUsersInRoom = channel.unary_unary(
                '/database.DatabaseService/GetUsersInRoom',
                request_serializer=app_dot_protos_dot_database__pb2.GetUsersInRoomRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_database__pb2.GetUsersInRoomResponse.FromString,
                )


class DatabaseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevicesInRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUserPreferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUserToRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUserFromRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersInRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRoom,
                    request_deserializer=app_dot_protos_dot_database__pb2.AddRoomRequest.FromString,
                    response_serializer=app_dot_protos_dot_database__pb2.AddRoomResponse.SerializeToString,
            ),
            'GetRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoom,
                    request_deserializer=app_dot_protos_dot_database__pb2.GetRoomRequest.FromString,
                    response_serializer=app_dot_protos_dot_database__pb2.GetRoomResponse.SerializeToString,
            ),
            'GetAllRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllRooms,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=app_dot_protos_dot_database__pb2.GetAllRoomsResponse.SerializeToString,
            ),
            'AddDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDevice,
                    request_deserializer=app_dot_protos_dot_database__pb2.AddDeviceRequest.FromString,
                    response_serializer=app_dot_protos_dot_database__pb2.AddDeviceResponse.SerializeToString,
            ),
            'GetDevicesInRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevicesInRoom,
                    request_deserializer=app_dot_protos_dot_database__pb2.GetDevicesInRoomRequest.FromString,
                    response_serializer=app_dot_protos_dot_database__pb2.GetDevicesInRoomResponse.SerializeToString,
            ),
            'AddUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUser,
                    request_deserializer=app_dot_protos_dot_database__pb2.AddUserRequest.FromString,
                    response_serializer=app_dot_protos_dot_database__pb2.AddUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=app_dot_protos_dot_database__pb2.GetUserRequest.FromString,
                    response_serializer=app_dot_protos_dot_database__pb2.GetUserResponse.SerializeToString,
            ),
            'SetUserPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUserPreferences,
                    request_deserializer=app_dot_protos_dot_database__pb2.SetUserPreferencesRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddUserToRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUserToRoom,
                    request_deserializer=app_dot_protos_dot_database__pb2.AddUserToRoomRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveUserFromRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUserFromRoom,
                    request_deserializer=app_dot_protos_dot_database__pb2.RemoveUserFromRoomRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetUsersInRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersInRoom,
                    request_deserializer=app_dot_protos_dot_database__pb2.GetUsersInRoomRequest.FromString,
                    response_serializer=app_dot_protos_dot_database__pb2.GetUsersInRoomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'database.DatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatabaseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/AddRoom',
            app_dot_protos_dot_database__pb2.AddRoomRequest.SerializeToString,
            app_dot_protos_dot_database__pb2.AddRoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/GetRoom',
            app_dot_protos_dot_database__pb2.GetRoomRequest.SerializeToString,
            app_dot_protos_dot_database__pb2.GetRoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/GetAllRooms',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            app_dot_protos_dot_database__pb2.GetAllRoomsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/AddDevice',
            app_dot_protos_dot_database__pb2.AddDeviceRequest.SerializeToString,
            app_dot_protos_dot_database__pb2.AddDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDevicesInRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/GetDevicesInRoom',
            app_dot_protos_dot_database__pb2.GetDevicesInRoomRequest.SerializeToString,
            app_dot_protos_dot_database__pb2.GetDevicesInRoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/AddUser',
            app_dot_protos_dot_database__pb2.AddUserRequest.SerializeToString,
            app_dot_protos_dot_database__pb2.AddUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/GetUser',
            app_dot_protos_dot_database__pb2.GetUserRequest.SerializeToString,
            app_dot_protos_dot_database__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetUserPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/SetUserPreferences',
            app_dot_protos_dot_database__pb2.SetUserPreferencesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddUserToRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/AddUserToRoom',
            app_dot_protos_dot_database__pb2.AddUserToRoomRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveUserFromRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/RemoveUserFromRoom',
            app_dot_protos_dot_database__pb2.RemoveUserFromRoomRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUsersInRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/GetUsersInRoom',
            app_dot_protos_dot_database__pb2.GetUsersInRoomRequest.SerializeToString,
            app_dot_protos_dot_database__pb2.GetUsersInRoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
