# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.protos import influxdb_pb2 as app_dot_protos_dot_influxdb__pb2


class InfluxdbServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteMeasurement = channel.unary_unary(
                '/influxdb.InfluxdbService/WriteMeasurement',
                request_serializer=app_dot_protos_dot_influxdb__pb2.WriteMeasurementRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_influxdb__pb2.WriteMeasurementResponse.FromString,
                )
        self.ReadMeasurements = channel.unary_unary(
                '/influxdb.InfluxdbService/ReadMeasurements',
                request_serializer=app_dot_protos_dot_influxdb__pb2.ReadMeasurementsRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_influxdb__pb2.ReadMeasurementsResponse.FromString,
                )


class InfluxdbServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteMeasurement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMeasurements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InfluxdbServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteMeasurement': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteMeasurement,
                    request_deserializer=app_dot_protos_dot_influxdb__pb2.WriteMeasurementRequest.FromString,
                    response_serializer=app_dot_protos_dot_influxdb__pb2.WriteMeasurementResponse.SerializeToString,
            ),
            'ReadMeasurements': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadMeasurements,
                    request_deserializer=app_dot_protos_dot_influxdb__pb2.ReadMeasurementsRequest.FromString,
                    response_serializer=app_dot_protos_dot_influxdb__pb2.ReadMeasurementsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'influxdb.InfluxdbService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InfluxdbService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteMeasurement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/influxdb.InfluxdbService/WriteMeasurement',
            app_dot_protos_dot_influxdb__pb2.WriteMeasurementRequest.SerializeToString,
            app_dot_protos_dot_influxdb__pb2.WriteMeasurementResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadMeasurements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/influxdb.InfluxdbService/ReadMeasurements',
            app_dot_protos_dot_influxdb__pb2.ReadMeasurementsRequest.SerializeToString,
            app_dot_protos_dot_influxdb__pb2.ReadMeasurementsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
